package sample_team.module.complex.police.observation;

import adf.core.agent.action.Action;
import adf.core.agent.action.common.ActionMove;
import adf.core.agent.action.common.ActionRest;
import adf.core.agent.action.police.ActionClear;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import rescuecore2.worldmodel.EntityID;

/**
 * Competition-grade observation metrics for one Police Force agent.
 *
 * This class never selects targets, changes paths, clears blockades,
 * or changes Police actions.
 *
 * It only records results generated by the official ADF modules.
 */
public final class URFPoliceMetrics {
  private static final Map<Integer, URFPoliceMetrics> INSTANCES = new ConcurrentHashMap<>();

  private final int agentId;

  private int time;

  private EntityID currentPosition;
  private EntityID previousPosition;
  private EntityID selectedTarget;
  private EntityID lastClearTarget;

  private double currentX;
  private double currentY;
  private double previousX;
  private double previousY;

  private double lastStepDistance;
  private double totalObservedDisplacement;

  private URFActionType lastActionType;
  private URFActionSource lastActionSource;

  /*
   * Class simple name of an Action the observation layer does not
   * model. Kept so the action log field is unchanged for OTHER.
   */
  private String otherActionLabel;

  private List<EntityID> lastPath;
  private int lastPathLength;

  private boolean lastMoveUsesPosition;
  private int lastMoveX;
  private int lastMoveY;

  private boolean lastClearUsesBlockadeTarget;
  private int lastClearX;
  private int lastClearY;

  private int moveCount;
  private int clearCount;
  private int restCount;
  private int otherActionCount;

  private int targetChangeCount;

  private int samePositionStreak;
  private int maxSamePositionStreak;

  private boolean possibleStuck;

  private long decisionTimeMillis;
  private long totalDecisionTimeMillis;
  private int decisionTimeSamples;

  // PO-5: CLEAR module statistics.
  private EntityID lastClearRequestTarget;

  private int clearModuleCallCount;
  private int clearModuleNullResultCount;

  private int clearModuleActionClearCount;
  private int clearModuleActionMoveCount;
  private int clearModuleActionRestCount;

  private long lastClearCalcNanos;
  private long totalClearCalcNanos;

  // PO-6: MOVE module statistics.
  private EntityID lastMoveRequestTarget;

  private int moveModuleCallCount;
  private int moveModuleNullResultCount;

  private int moveModuleActionMoveCount;
  private int moveModuleActionRestCount;

  private int fallbackRestCount;

  private long lastMoveCalcNanos;
  private long totalMoveCalcNanos;

  // Prevent accidental double counting.
  private int lastFinalActionTime;

  private URFPoliceMetrics(EntityID agentId) {

    this.agentId = agentId.getValue();

    this.time = -1;

    this.lastFinalActionTime = -1;

    this.lastActionType = URFActionType.NONE;
    this.lastActionSource = URFActionSource.NONE;
    this.otherActionLabel = null;

    this.lastPath = Collections.emptyList();

    this.currentX = Double.NaN;
    this.currentY = Double.NaN;

    this.previousX = Double.NaN;
    this.previousY = Double.NaN;
  }

  public static URFPoliceMetrics forAgent(EntityID agentId) {

    if (agentId == null) {
      throw new IllegalArgumentException(
          "agentId must not be null");
    }

    return INSTANCES.computeIfAbsent(agentId.getValue(),id -> new URFPoliceMetrics(agentId));
  }

  public static void resetAgent(EntityID agentId) {
    if (agentId != null) {
      INSTANCES.remove(agentId.getValue());
    }
  }

  public synchronized void recordPosition(int simulationTime, EntityID position) {
    recordPosition(simulationTime, position, Double.NaN, Double.NaN);
  }

  public synchronized void recordPosition(int simulationTime, EntityID position,
                                          double x, double y) {
    // Do not count the same timestep twice.
    if (simulationTime == this.time) {

      this.currentPosition = position;

      if (Double.isFinite(x) && Double.isFinite(y)) {
        this.currentX = x;
        this.currentY = y;
      }

      return;
    }

    this.time = simulationTime;
    this.previousPosition = this.currentPosition;
    this.currentPosition = position;
    this.previousX = this.currentX;
    this.previousY = this.currentY;
    this.currentX = x;
    this.currentY = y;

    if (Double.isFinite(this.previousX) && Double.isFinite(this.previousY) && 
        Double.isFinite(this.currentX) && Double.isFinite(this.currentY)) {
      double dx = this.currentX - this.previousX;
      double dy = this.currentY - this.previousY;

      this.lastStepDistance =
          Math.hypot(dx, dy);
      this.totalObservedDisplacement +=
          this.lastStepDistance;
    }
    else {
      this.lastStepDistance = 0.0;
    }

    if (this.previousPosition != null && this.previousPosition.equals(this.currentPosition)) {
      this.samePositionStreak++;
      if (this.samePositionStreak > this.maxSamePositionStreak) {
        this.maxSamePositionStreak = this.samePositionStreak;
      }
    } 
    else {
      this.samePositionStreak = 0;
    }
  }

  public synchronized void recordTarget(EntityID target) {
    if (this.selectedTarget == null && target == null) {
      return;
    }
    if (this.selectedTarget == null || !this.selectedTarget.equals(target)) {
      this.targetChangeCount++;
    }
    this.selectedTarget = target;
  }

  /**
   * Backward-compatible PO-3 method.
   */
  public synchronized void recordAction(Action action) {
    recordActionInternal(action, URFActionSource.UNSPECIFIED);
  }

  /**
   * PO-5.
   *
   * Records the result generated by
   * DefaultExtActionClear.
   */
  public synchronized void recordClearModuleResult(
      int simulationTime, EntityID requestedTarget, Action action, long calcNanos) {
    this.lastClearRequestTarget = requestedTarget;
    this.clearModuleCallCount++;
    this.lastClearCalcNanos = Math.max(0L, calcNanos);
    this.totalClearCalcNanos += this.lastClearCalcNanos;

    if (action == null) {
      this.clearModuleNullResultCount++;
      return;
    }

    if (action instanceof ActionClear) {
      this.clearModuleActionClearCount++;
    } 
    else if (action instanceof ActionMove) {
      this.clearModuleActionMoveCount++;
    } 
    else if (action instanceof ActionRest) {
      this.clearModuleActionRestCount++;
    }

    recordFinalActionInternal(simulationTime, action, URFActionSource.CLEAR_MODULE);
  }

  /**
   * PO-6.
   *
   * Records the result generated by
   * DefaultExtActionMove.
   *
   * If MOVE returns null, the unchanged
   * DefaultTacticsPoliceForce immediately
   * returns ActionRest.
   */
  public synchronized void recordMoveModuleResult(int simulationTime, EntityID requestedTarget,
      						  Action action, long calcNanos) {
    this.lastMoveRequestTarget = requestedTarget;
    this.moveModuleCallCount++;
    this.lastMoveCalcNanos = Math.max(0L, calcNanos);
    this.totalMoveCalcNanos += this.lastMoveCalcNanos;

    if (action == null) {
      this.moveModuleNullResultCount++;
      this.fallbackRestCount++;

      // Observation only.
      // We do not change DefaultExtActionMove.result.
      recordFinalActionInternal(simulationTime, new ActionRest(),
          URFActionSource.TACTICS_FALLBACK_REST);
      return;
    }
    if (action instanceof ActionMove) {
      this.moveModuleActionMoveCount++;
    } 
    else if (action instanceof ActionRest) {
      this.moveModuleActionRestCount++;
    }
    recordFinalActionInternal(simulationTime, action, URFActionSource.MOVE_MODULE);
  }

  private void recordFinalActionInternal(int simulationTime, Action action,
      URFActionSource source) {
    if (simulationTime == this.lastFinalActionTime) {
      updateLastActionSnapshot(action, source);
      return;
    }

    this.lastFinalActionTime = simulationTime;

    recordActionInternal(action, source);
  }

  private void recordActionInternal(Action action, URFActionSource source) {
    this.lastActionSource = source == null ? URFActionSource.UNKNOWN : source;

    resetLastActionDetails();

    if (action == null) {
      this.lastActionType = URFActionType.NONE;
      return;
    }

    if (action instanceof ActionMove) {
      ActionMove move = (ActionMove) action;

      this.lastActionType = URFActionType.MOVE;
      this.moveCount++;
      this.lastPath = Collections.unmodifiableList(new ArrayList<>(move.getPath()));
      this.lastPathLength = this.lastPath.size();
      this.lastMoveUsesPosition = move.getUsePosition();
      this.lastMoveX = move.getPosX();
      this.lastMoveY = move.getPosY();
      return;
    }

    if (action instanceof ActionClear) {
      ActionClear clear = (ActionClear) action;
      this.lastActionType = URFActionType.CLEAR;
      this.clearCount++;
      this.lastClearTarget = clear.getTarget();
      this.lastClearUsesBlockadeTarget = clear.getUseOldFunction();
      this.lastClearX = clear.getPosX();
      this.lastClearY = clear.getPosY();

      return;
    }

    if (action instanceof ActionRest) {
      this.lastActionType = URFActionType.REST;
      this.restCount++;
      return;
    }

    this.lastActionType = URFActionType.OTHER;
    this.otherActionLabel = action.getClass().getSimpleName();
    this.otherActionCount++;
  }

  private void updateLastActionSnapshot(Action action, URFActionSource source) {
    this.lastActionSource = source == null ? URFActionSource.UNKNOWN : source;

    resetLastActionDetails();

    if (action == null) {
      this.lastActionType = URFActionType.NONE;
      return;
    }

    if (action instanceof ActionMove) {
      ActionMove move = (ActionMove) action;

      this.lastActionType = URFActionType.MOVE;
      this.lastPath = Collections.unmodifiableList(new ArrayList<>(move.getPath()));
      this.lastPathLength = this.lastPath.size();
      this.lastMoveUsesPosition = move.getUsePosition();
      this.lastMoveX = move.getPosX();
      this.lastMoveY = move.getPosY();

      return;
    }

    if (action instanceof ActionClear) {
      ActionClear clear = (ActionClear) action;
      this.lastActionType = URFActionType.CLEAR;
      this.lastClearTarget = clear.getTarget();
      this.lastClearUsesBlockadeTarget = clear.getUseOldFunction();
      this.lastClearX = clear.getPosX();
      this.lastClearY = clear.getPosY();

      return;
    }

    if (action instanceof ActionRest) {
      this.lastActionType = URFActionType.REST;
      return;
    }

    this.lastActionType = URFActionType.OTHER;
    this.otherActionLabel = action.getClass().getSimpleName();
  }

  private void resetLastActionDetails() {
    this.otherActionLabel = null;
    this.lastPath = Collections.emptyList();
    this.lastPathLength = 0;
    this.lastClearTarget = null;
    this.lastMoveUsesPosition = false;

    this.lastMoveX = 0;
    this.lastMoveY = 0;
    this.lastClearUsesBlockadeTarget = false;

    this.lastClearX = 0;
    this.lastClearY = 0;
  }

  public synchronized void recordDecisionTime(long milliseconds) {
    this.decisionTimeMillis = Math.max(0L, milliseconds);
    this.totalDecisionTimeMillis += this.decisionTimeMillis;
    this.decisionTimeSamples++;
  }

  public synchronized void setPossibleStuck(boolean possibleStuck) {
    this.possibleStuck = possibleStuck;
  }

  public int getAgentId() {
    return this.agentId;
  }

  public synchronized int getTime() {
    return this.time;
  }

  public synchronized EntityID getCurrentPosition() {
    return this.currentPosition;
  }

  public synchronized EntityID getPreviousPosition() {
    return this.previousPosition;
  }

  public synchronized double getCurrentX() {
    return this.currentX;
  }

  public synchronized double getCurrentY() {
    return this.currentY;
  }

  public synchronized double getPreviousX() {
    return this.previousX;
  }

  public synchronized double getPreviousY() {
    return this.previousY;
  }

  public synchronized double getLastStepDistance() {
    return this.lastStepDistance;
  }

  public synchronized double getTotalObservedDisplacement() {
    return this.totalObservedDisplacement;
  }

  public synchronized EntityID getSelectedTarget() {
    return this.selectedTarget;
  }

  public synchronized EntityID getLastClearTarget() {
    return this.lastClearTarget;
  }

  public synchronized URFActionType getLastActionType() {
    return this.lastActionType;
  }

  public synchronized URFActionSource getLastActionSource() {
    return this.lastActionSource;
  }

  /**
   * @return the text previously written to the action log and CSV field
   */
  public synchronized String getLastActionLabel() {
    if (this.lastActionType == URFActionType.OTHER
        && this.otherActionLabel != null) {
      return this.otherActionLabel;
    }
    return this.lastActionType.name();
  }

  public synchronized List<EntityID> getLastPath() {
    return this.lastPath;
  }

  public synchronized int getLastPathLength() {
    return this.lastPathLength;
  }

  public synchronized boolean isLastMoveUsingPosition() {
    return this.lastMoveUsesPosition;
  }

  public synchronized int getLastMoveX() {
    return this.lastMoveX;
  }

  public synchronized int getLastMoveY() {
    return this.lastMoveY;
  }

  public synchronized boolean isLastClearUsingBlockadeTarget() {
    return this.lastClearUsesBlockadeTarget;
  }

  public synchronized int getLastClearX() {
    return this.lastClearX;
  }

  public synchronized int getLastClearY() {
    return this.lastClearY;
  }

  public synchronized int getMoveCount() {
    return this.moveCount;
  }

  public synchronized int getClearCount() {
    return this.clearCount;
  }

  public synchronized int getRestCount() {
    return this.restCount;
  }

  public synchronized int getOtherActionCount() {
    return this.otherActionCount;
  }

  public synchronized int getTargetChangeCount() {
    return this.targetChangeCount;
  }

  public synchronized int getSamePositionStreak() {
    return this.samePositionStreak;
  }

  public synchronized int getMaxSamePositionStreak() {
    return this.maxSamePositionStreak;
  }

  public synchronized boolean isPossibleStuck() {
    return this.possibleStuck;
  }

  public synchronized long getDecisionTimeMillis() {
    return this.decisionTimeMillis;
  }

  public synchronized double getAverageDecisionTimeMillis() {
    if (this.decisionTimeSamples == 0) {
      return 0.0;
    }
    return (double) this.totalDecisionTimeMillis / this.decisionTimeSamples;
  }

  public synchronized EntityID getLastClearRequestTarget() {
    return this.lastClearRequestTarget;
  }

  public synchronized int getClearModuleCallCount() {
    return this.clearModuleCallCount;
  }

  public synchronized int getClearModuleNullResultCount() {
    return this.clearModuleNullResultCount;
  }

  public synchronized int getClearModuleActionClearCount() {
    return this.clearModuleActionClearCount;
  }

  public synchronized int getClearModuleActionMoveCount() {
    return this.clearModuleActionMoveCount;
  }

  public synchronized int getClearModuleActionRestCount() {
    return this.clearModuleActionRestCount;
  }

  public synchronized EntityID getLastMoveRequestTarget() {
    return this.lastMoveRequestTarget;
  }

  public synchronized int getMoveModuleCallCount() {
    return this.moveModuleCallCount;
  }

  public synchronized int getMoveModuleNullResultCount() {
    return this.moveModuleNullResultCount;
  }

  public synchronized int getMoveModuleActionMoveCount() {
    return this.moveModuleActionMoveCount;
  }

  public synchronized int getMoveModuleActionRestCount() {
    return this.moveModuleActionRestCount;
  }

  public synchronized int getFallbackRestCount() {
    return this.fallbackRestCount;
  }

  public synchronized long getLastClearCalcNanos() {
    return this.lastClearCalcNanos;
  }

  public synchronized long getLastMoveCalcNanos() {
    return this.lastMoveCalcNanos;
  }

  public synchronized double getAverageClearCalcMicros() {
    if (this.clearModuleCallCount == 0) {
      return 0.0;
    }
    return (this.totalClearCalcNanos / 1000.0) / this.clearModuleCallCount;
  }

  public synchronized double getAverageMoveCalcMicros() {
    if (this.moveModuleCallCount == 0) {
      return 0.0;
    }
    return (this.totalMoveCalcNanos / 1000.0) / this.moveModuleCallCount;
  }

  public synchronized String toLogLine() {
    return "URF_POLICE_METRICS"
        + " time=" + this.time
        + " agent=" + this.agentId
        + " position=" + idValue(this.currentPosition)
        + " x=" + finiteValue(this.currentX)
        + " y=" + finiteValue(this.currentY)
        + " stepDistance=" + this.lastStepDistance
        + " totalDisplacement=" + this.totalObservedDisplacement
        + " target=" + idValue(this.selectedTarget)
        + " action=" + this.getLastActionLabel()
        + " actionSource=" + this.lastActionSource
        + " pathLength=" + this.lastPathLength
        + " moveUsePosition=" + this.lastMoveUsesPosition
        + " moveX=" + this.lastMoveX
        + " moveY=" + this.lastMoveY
        + " clearTarget=" + idValue(this.lastClearTarget)
        + " clearUseTarget=" + this.lastClearUsesBlockadeTarget
        + " clearX=" + this.lastClearX
        + " clearY=" + this.lastClearY
        + " moveCount=" + this.moveCount
        + " clearCount=" + this.clearCount
        + " restCount=" + this.restCount
        + " otherActionCount=" + this.otherActionCount
        + " targetChangeCount=" + this.targetChangeCount
        + " samePositionStreak=" + this.samePositionStreak
        + " maxSamePositionStreak=" + this.maxSamePositionStreak
        + " possibleStuck=" + this.possibleStuck
        + " clearRequestTarget=" + idValue(this.lastClearRequestTarget)
        + " clearModuleCalls=" + this.clearModuleCallCount
        + " clearNullResults=" + this.clearModuleNullResultCount
        + " clearResults=" + this.clearModuleActionClearCount
        + " clearMoveResults=" + this.clearModuleActionMoveCount
        + " clearRestResults=" + this.clearModuleActionRestCount
        + " moveRequestTarget=" + idValue(this.lastMoveRequestTarget)
        + " moveModuleCalls=" + this.moveModuleCallCount
        + " moveNullResults=" + this.moveModuleNullResultCount
        + " moveResults=" + this.moveModuleActionMoveCount
        + " moveRestResults=" + this.moveModuleActionRestCount
        + " fallbackRestCount=" + this.fallbackRestCount
        + " clearCalcUs=" + nanosToMicros(this.lastClearCalcNanos)
        + " moveCalcUs=" + nanosToMicros(this.lastMoveCalcNanos)
        + " decisionTimeMs=" + this.decisionTimeMillis
        + " averageDecisionTimeMs=" + getAverageDecisionTimeMillis();
  }

  private static String idValue(EntityID id) {
    if (id == null) {
      return "null";
    }
    return Integer.toString(id.getValue());
  }

  private static String finiteValue(double value) {
    if (!Double.isFinite(value)) {
      return "NaN";
    }
    return Double.toString(value);
  }

  private static double nanosToMicros(long nanos) {
    return nanos / 1000.0;
  }
}